### ISSUE TITLE
run and run2

### ISSUE THREAD

**Issue by carlosypunto** [truizlop/IntroToBow#1]
As in presentation I'm confused by `run` and `run2` functions issue I've renamed `BirthdayCurrying.run2` in page one to `run`, for me is working fine, it's just a comment. BTW, You've just published `Rename toOption/fromOption` pull in library repo, can I make a pull with this change, updating Podfile to 
 `pod 'Bow', :git => 'https://github.com/bow-swift/bow.git', :branch => 'master'` in pod file?

**Comment by carlosypunto** [comment]
In case you accept I recommend to include `Pod/` directory in `.gitignore` file, for reduce git size, but it would require the users to do `pod install` after cloning the repo.

**Comment by carlosypunto** [comment]
Sorry, I have rushed, the pull is not yet merged

**Comment by truizlop** [comment]
Thanks! I was having compile time issues when I was using `run`, but it might be related to something else. As for the version update, once we publish a new Bow version I will update everything in this repo. I prefer to rely on published versions rather than the ongoing development, as it may break things.
